//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHangEntities : DbContext
    {
        public BanHangEntities()
            : base("name=BanHangEntities")
        {
            //Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<congnghe> congnghes { get; set; }
        public DbSet<chitiet_donhang> chitiet_donhang { get; set; }
        public DbSet<chitiet_hoadon> chitiet_hoadon { get; set; }
        public DbSet<donhang> donhangs { get; set; }
        public DbSet<dungluong> dungluongs { get; set; }
        public DbSet<hangsanxuat> hangsanxuats { get; set; }
        public DbSet<hoadon> hoadons { get; set; }
        public DbSet<khachhang> khachhangs { get; set; }
        public DbSet<loai> loais { get; set; }
        public DbSet<nhacungcap> nhacungcaps { get; set; }
        public DbSet<nhanvien> nhanviens { get; set; }
        public DbSet<quangcao> quangcaos { get; set; }
        public DbSet<sanpham> sanphams { get; set; }
    }
}
